### ISSUE TITLE
Consistent naming

### ISSUE THREAD

**Issue by sz-piotr** [dethcrypto/earl#104]
The website: `https://earljs.dev/`
The package: `earljs`
The repo: `earl`
The organisation `earl-js`

Can we change everything to be `earljs`?

**Comment by sz-piotr** [comment]
Additionally we could also change the logo to spell `earljs`. I've included an alternative version based on tea labels. The idea is that this is something that you'd see on a box of tea.

<img width="466" alt="Screenshot 2020-12-14 at 11 09 15" src="https://user-images.githubusercontent.com/17070569/102068571-e05a4f80-3dfc-11eb-9e3f-6989f1a2b233.png">

**Comment by sz-piotr** [comment]
@krzkaczor

**Comment by krzkaczor** [comment]
The naming pattern might seem random but it's not that bad 😆 Here's a priority of names I followed:

1. earl - canonical name
2. earljs 
3. earl-js

I always try to pick them in this order. The thing is that shorter names are often not available. That's why the GitHub Org is named `earl-js` - @earljs is not available. 

This is important to remember because either way we won't end up with consistent naming. That being said, I don't think this is a problem at all. It's actually a very common situation these days, even for well-funded companies (just take a look at handles used by `notion`). As long as it's easy to find it using google it's fine.

I would prefer to keep calling project `earl` as it's super short and goes nicely in pair with `chai`.  I add the "js" suffix only when it's necessary.

One thing that we could improve is to try to get in touch with `earl` npm package owner and convince him to donate the package name. I will try again today. Let's see what happens.

**Comment by krzkaczor** [comment]
@magnetik, I noticed you're the owner of `earl` npm package. The package doesn't seem to be used these days. Would you consider donating it for this project? Thanks!
